GET http://localhost/api/reservations HTTP/1.1

###
POST http://localhost/api/reservations HTTP/1.1
content-type: application/json

{
  "startDate": "2023-03-10T22:00:44.536Z",
  "endDate": "2023-03-10T22:30:44.536Z",
  "allDay": false,
  "courtId": "6409d222a92efd0013af025f",
  "playerId": "640c555a0a48690019e3abc8"
}

###
DELETE http://localhost/api/reservations/640966afc8dc380013b3db57 HTTP/1.1

###
PUT http://localhost/api/reservations/64096c8bc8dc380013b3db5f HTTP/1.1
content-type: application/json

{
    "player_name" : "Test 2"
}